kubectl: Update repo
In
https://github.com/isovalent/hubble-fgs/actions/runs/8140230673/job/22246694503?pr=4063
we get the following error:
Get:1 http://deb.debian.org/debian sid InRelease [198 kB]
Get:2 https://download.docker.com/linux/debian bullseye InRelease [43.3 kB]
Get:3 http://deb.debian.org/debian sid/main amd64 Packages.diff/Index [63.6 kB]
Get:5 http://deb.debian.org/debian sid/main Translation-en.diff/Index [63.6 kB]
Ign:4 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Get:6 http://deb.debian.org/debian sid/main amd64 Packages T-2024-03-04-0813.24-F-2024-02-21-1406.36.pdiff [1400 kB]
Get:7 https://download.docker.com/linux/debian bullseye/stable amd64 Packages [31.9 kB]
Get:6 http://deb.debian.org/debian sid/main amd64 Packages T-2024-03-04-0813.24-F-2024-02-21-1406.36.pdiff [1400 kB]
Get:8 http://deb.debian.org/debian sid/main Translation-en T-2024-03-04-0813.24-F-2024-02-21-1406.36.pdiff [275 kB]
Err:9 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 142.251.167.102 443]
Get:8 http://deb.debian.org/debian sid/main Translation-en T-2024-03-04-0813.24-F-2024-02-21-1406.36.pdiff [275 kB]
Reading package lists...
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' no longer has a Release file.
Error: Process completed with exit code 100.

This PR updates the repo using the intructions provided here:
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management.

Signed-off-by: Anastasios Papagiannis <tasos.papagiannnis@gmail.com>