Fix local builds
When trying to build images for a custom kernel locally, it fails with
the following error:

    for v in my-kernel ; do \
       docker build --no-cache \
          --build-arg KERNEL_BUILDER_TAG=main \
          --build-arg KERNEL_VER=$v \
          --platform=linux/amd64 \
          -f dockerfiles/kernel-images -t quay.io/lvh-images/kernel-images-ci:$v . ; \
    done
    [...]
    for v in my-kernel ; do \
        docker build --no-cache \
          --build-arg KERNEL_VER=$v \
          --build-arg KERNEL_IMAGE_TAG=$v-main \
          --build-arg ROOT_BUILDER_TAG=main \
          --build-arg ROOT_IMAGES_TAG=main \
          -f dockerfiles/kind-images -t quay.io/lvh-images/kind-ci:$v . ; \
    done
    [...]
    ------
     > [internal] load metadata for quay.io/lvh-images/kernel-images-ci:my-kernel-main:
    ------
    kind-images:11
    --------------------
       9 |
      10 |     FROM quay.io/lvh-images/root-images-ci:"${ROOT_IMAGES_TAG}" AS root-images
      11 | >>> FROM quay.io/lvh-images/kernel-images-ci:"${KERNEL_IMAGE_TAG}" AS kimg
      12 |     FROM quay.io/lvh-images/lvh:v0.0.19 AS lvh
      13 |     FROM ubuntu:rolling AS builder
    --------------------
    ERROR: failed to solve: failed to resolve source metadata for quay.io/lvh-images/kernel-images-ci:my-kernel-main: quay.io/lvh-images/kernel-images-ci:my-kernel-main: not found
    make: *** [Makefile:63: kind] Error 1

It seems we build the kernel-images-ci image without a -main suffix, but
then expect that suffix when building other dependent images. This
commit fixes it by dropping the suffix altogether.

Signed-off-by: Paul Chaignon <paul.chaignon@gmail.com>